### ISSUE TITLE
mozart-1.4.0 does not compile on Fedora 14 i686 (gcc version 4.5.1)

### ISSUE THREAD

**Issue by sjmackenzie** [mozart/mozart#157]
The mozart-1.4.0 sources have a syntax errors:

urlc.cc: In member function ‘int urlc::parse_ftp(const char_)’:
urlc.cc:628:32: error: invalid conversion from ‘const char_’ to ‘char_’
urlc.cc:629:28: error: invalid conversion from ‘const char_’ to ‘char_’
urlc.cc:633:28: error: invalid conversion from ‘const char_’ to ‘char_’
urlc.cc:634:30: error: invalid conversion from ‘const char_’ to ‘char_’
urlc.cc: In member function ‘int urlc::get_ftp(char_)’:
urlc.cc:927:39: warning: deprecated conversion from string constant to ‘char_’
urlc.cc: In member function ‘int urlc::parse_http(const char_)’:
urlc.cc:1143:32: error: invalid conversion from ‘const char_’ to ‘char_’
urlc.cc:1144:31: error: invalid conversion from ‘const char_’ to ‘char_’

The generic linux rpm also does not install correctly:

root@localhost:/home/kbriggs/Downloads> rpm -i mozart-1.4.0.20080704-16189.i386.rpm
error: unpacking of archive failed on file /usr/lib/mozart/platform/linux-i486/lib/libgcc_s.so.1;4d4ff7ff: cpio: Digest
mismatch

Keith
